import { volkhov } from "./fonts";
import "./globals.css";

export const metadata = {
    title: "Explore | Tour Book",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={volkhov.className}>{children}</body>
        </html>
    );
}
